[project]
name = "hydro-forecasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "“CooperBigFoot”", email = "“nlazaro@student.ethz.ch”" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
hydro-forecasting = "hydro_forecasting:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
