[project]
name = "hydro-forecasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CooperBigFoot", email = "nlazaro@student.ethz.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "lightning>=2.5.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "polars>=1.27.1",
    "returns>=0.25.0",
    "seaborn>=0.13.2",
    "torch>=2.6.0",
]

[project.scripts]
hydro-forecasting = "hydro_forecasting:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
