[project]
name = "hydro-forecasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CooperBigFoot", email = "nlazaro@student.ethz.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.0.1",
    "ipykernel>=6.29.5",
    "lightning>=2.5.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "returns>=0.25.0",
    "ruff>=0.11.5",
    "seaborn>=0.13.2",
    "torch>=2.6.0",
]

[project.scripts]
hydro-forecasting = "hydro_forecasting:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
# Tell hatchling to use the src layout
sources = ["src"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default.dependencies]
pytest = ">=8.3.5"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

# ✅ Add this section for pytest to include src/
[tool.pytest.ini_options]
pythonpath = ["src"]
