decoder_output_size: 16
dropout: 0.1
future_forcing_projection_size: 4
future_input_size: 9
group_identifier: gauge_id
hidden_size: 16
input_len: 70
input_size: 9
learning_rate: 0.001
num_decoder_layers: 2
num_encoder_layers: 2
output_len: 10
past_feature_projection_size: 4
scheduler_factor: 0.5
scheduler_patience: 5
static_size: 10
temporal_decoder_hidden_size: 16
use_layer_norm: true
